version: '3'
services:
  db:
    image: mysql:8.0
    command: '--default-authentication-plugin=mysql_native_password'
    environment:
      MYSQL_USER: webapp
      MYSQL_DATABASE: webapp
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - '43306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
      - './docker/db/conf.d:/etc/mysql/conf.d'

  redis:
    image: redis:5.0.12
    ports:
      - "26379:6379"

  web:
    image: graphql-web:latest
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    command: sh ./docker/web/commands.sh
    environment:
      PORT: 8080
    volumes:
      - ".:/webapp"
    ports:
      - "18080:8080"
    depends_on:
      - db
      - redis
    stdin_open: true
    tty: true

volumes:
  mysql-data:
