default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>
  timeout: 5000
  encoding: utf8
  username: <%= ENV.fetch('PRIMARY_DB_USERNAME', 'webapp') %>
  password: <%= ENV.fetch('PRIMARY_DB_PASSWORD', '123456') %>
  host: <%= ENV.fetch('PRIMARY_DB_HOST', 'db') %>

development:
  <<: *default
  database: webapp
